package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '03DeployToStaging'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("03DeployToStaging")) {
    expectSteps {
        script {
            name = "ISS Deploy"
            scriptContent = """
                rmdir /A /Q \inetpub\wwwroot
                            xcopy /S /I /Y app \inetpub\wwwroot\
            """.trimIndent()
        }
        script {
            name = "Browser Tests"
            scriptContent = "npm test -- --single-run --browser %Browser% --colors false --reporters teamcity"
        }
    }
    steps {
        items.removeAt(1)
    }
}
